server:
  port: 8086

spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://mongodb:27017/user

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka

jwt:
  secret: ${JWT_SECRET}
