server:
  port: 8068

spring:
  application:
    name: user-security
  data:
    mongodb:
      uri: mongodb://mongodb:27017/userSecurity

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka