spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
cloud:
  gateway:
    routes:
      - id: users
        uri: lb://user-service # lb indique un Load Balancer
        predicates:
          - Path=/user-service/**
      - id: vehicle
        uri: lb://vehicle-service
        predicates:
          - Path=/vehicle-service/**
