server:
  port: 9999

spring:
  application:
    name: api-gateway
  eureka:
    client:
      service-url:
        defaultZone: http://eureka:8761/eureka
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<remaining>.*), /${remaining}

        - id: vehicle-service
          uri: lb://VEHICLE-SERVICE
          predicates:
            - Path=/vehicle-service/**
          filters:
            - RewritePath=/vehicle-service/(?<remaining>.*), /${remaining}

        - id: annonce-service
          uri: lb://ANNONCE-SERVICE
          predicates:
            - Path=/annonce-service/**
          filters:
            - RewritePath=/annonce-service/(?<remaining>.*), /${remaining}

        - id: reservation-service
          uri: lb://RESERVATION-SERVICE
          predicates:
            - Path=/reservation-service/**
          filters:
            - RewritePath=/reservation-service/(?<remaining>.*), /${remaining}

        - id: appartement-service
          uri: lb://APPARTEMENT-SERVICE
          predicates:
            - Path=/appartement-service/**
          filters:
            - RewritePath=/appartement-service/(?<remaining>.*), /${remaining}

  logging:
    level:
      org.springframework.cloud.gateway: DEBUG
      org.springframework.web: DEBUG
      org.springframework.cloud: DEBUG
