server:
  port: 8092
spring:
  application:
    name: user-service
  cloud:
    discovery:
      enabled: true

  data:
    mongodb:
      uri: mongodb://mongodb:27017/vl
      database: users

eureka:
  client:
    register-with-eureka: true  # Inscrire le service dans Eureka
    fetch-registry: true  # Récupérer le registre des services
    service-url:
      defaultZone: http://eureka:8761/eureka  # URL de votre serveur Eureka
    instance:
      prefer-ip-address: true  # Permet d'utiliser l'IP au lieu du hostname
      instance-id: ${spring.application.name}:${random.value}
