server:
  port: 8761

#spring:
#  cloud:
#    compatibility-verifier:
#      enabled: false
#    config:
#      uri: http://config-server:9998
#      name: config-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    registry-fetch-interval-seconds: 30
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

  server:
    enable-self-preservation: false
    peer-node-read-timeout-ms: 10000
    wait-time-in-ms-when-sync-empty: 0
    eviction-interval-timer-in-ms: 60000

  instance:
    hostname: eureka
    prefer-ip-address: false
    health-check-url: http://eureka:8761/actuator/health  # Add this
    health-check-url-path: /actuator/health
    lease-renewal-interval-in-seconds: 60  # Default: 30 (reduce heartbeat frequency)
    #status-page-url-path: /actuator/info

logging:
  level:
    com.netflix.eureka: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info