server:
  port: 8081
spring:
  application:
    name: vehicle-service
  cloud:
    discovery:
      enabled: true  # Activer la découverte de service

  data:
    mongodb:
      uri: mongodb://localhost:27017/vl  # URL de connexion à MongoDB
      database: vehicules # Nom de la base de données

eureka:
  client:
    register-with-eureka: true  # Inscrire le service dans Eureka
    fetch-registry: true  # Récupérer le registre des services
    service-url:
      defaultZone: http://localhost:8761/eureka/  # URL de votre serveur Eureka
