server:
  port: 8084
spring:
  application:
    name: reservation-service  # Nom du service dans Eureka
  cloud:
    discovery:
      enabled: true  # Activer la découverte de service

  data:
    mongodb:
      uri: mongodb://localhost:27017/vl
      database: reservation

eureka:
  client:
    register-with-eureka: true  # Inscrire le service dans Eureka
    fetch-registry: true  # Récupérer le registre des services
    service-url:
      defaultZone: http://localhost:8761/eureka/  # URL de votre serveur Eureka
